controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scorbot_position_controller: #-------
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scorbot_position_controller: #---------
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    interface_name: position